name: ffi_cgo_ojichat

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  path: ^1.8.0

dev_dependencies:
  ffigen: ^3.0.0
  lints: ^1.0.1

ffigen:
  name: OjiChat
  description: Bindings to OjiChat.
  output: 'bin/library/generated_bindings.dart'
  headers:
    entry-points:
      - 'headers/libojichat.h'
