name: ffi_cgo_ojichat

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  path: ^1.7.0

dev_dependencies:
  ffigen: ^1.2.0
  pedantic: 1.9.2

ffigen:
  name: OjiChat
  description: Bindings to OjiChat.
  output: 'bin/library/generated_bindings.dart'
  headers:
    entry-points:
      - 'headers/libojichat.h'
